//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDongle.DongleServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DongleServer.DongleServiceContract")]
    public interface DongleServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/login", ReplyAction="http://tempuri.org/DongleServiceContract/loginResponse")]
        DongleService.Structs.LoginResponse login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/addNewUser", ReplyAction="http://tempuri.org/DongleServiceContract/addNewUserResponse")]
        DongleService.Structs.ExecuteResponse addNewUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/updatePassword", ReplyAction="http://tempuri.org/DongleServiceContract/updatePasswordResponse")]
        DongleService.Structs.ExecuteResponse updatePassword(long uid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/sendSMS", ReplyAction="http://tempuri.org/DongleServiceContract/sendSMSResponse")]
        DongleService.Structs.ExecuteResponse sendSMS(long senderId, string to, string messsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/sendGroupSMS", ReplyAction="http://tempuri.org/DongleServiceContract/sendGroupSMSResponse")]
        DongleService.Structs.ExecuteResponse sendGroupSMS(long senderId, long groupId, string messsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/getAllGroups", ReplyAction="http://tempuri.org/DongleServiceContract/getAllGroupsResponse")]
        System.Collections.Generic.KeyValuePair<long, string>[] getAllGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DongleServiceContract/getUserInfo", ReplyAction="http://tempuri.org/DongleServiceContract/getUserInfoResponse")]
        DongleService.Structs.UserObject getUserInfo(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DongleServiceContractChannel : LocalDongle.DongleServer.DongleServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DongleServiceContractClient : System.ServiceModel.ClientBase<LocalDongle.DongleServer.DongleServiceContract>, LocalDongle.DongleServer.DongleServiceContract {
        
        public DongleServiceContractClient() {
        }
        
        public DongleServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DongleServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DongleServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DongleServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DongleService.Structs.LoginResponse login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public DongleService.Structs.ExecuteResponse addNewUser(string username, string password) {
            return base.Channel.addNewUser(username, password);
        }
        
        public DongleService.Structs.ExecuteResponse updatePassword(long uid, string password) {
            return base.Channel.updatePassword(uid, password);
        }
        
        public DongleService.Structs.ExecuteResponse sendSMS(long senderId, string to, string messsage) {
            return base.Channel.sendSMS(senderId, to, messsage);
        }
        
        public DongleService.Structs.ExecuteResponse sendGroupSMS(long senderId, long groupId, string messsage) {
            return base.Channel.sendGroupSMS(senderId, groupId, messsage);
        }
        
        public System.Collections.Generic.KeyValuePair<long, string>[] getAllGroups() {
            return base.Channel.getAllGroups();
        }
        
        public DongleService.Structs.UserObject getUserInfo(long id) {
            return base.Channel.getUserInfo(id);
        }
    }
}
