//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDongle.DongleServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DongleServer.dongleServiceContract")]
    public interface dongleServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dongleServiceContract/login", ReplyAction="http://tempuri.org/dongleServiceContract/loginResponse")]
        dongleService.loginResponse login(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface dongleServiceContractChannel : LocalDongle.DongleServer.dongleServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dongleServiceContractClient : System.ServiceModel.ClientBase<LocalDongle.DongleServer.dongleServiceContract>, LocalDongle.DongleServer.dongleServiceContract {
        
        public dongleServiceContractClient() {
        }
        
        public dongleServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public dongleServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dongleServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dongleServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public dongleService.loginResponse login(string username, string password) {
            return base.Channel.login(username, password);
        }
    }
}
